### ISSUE TITLE
Add service selection for blockchain systemd units

### ISSUE THREAD

**Issue by lazzarello** [quantstamp/eth-router#15]
[The blockchain role](https://github.com/lazzarello/eth-router/blob/master/deploy/ansible/roles/blockchain/tasks/main.yml#L39) installs and starts systemd services for all networks defined in [the playbook variables](https://github.com/lazzarello/eth-router/blob/master/deploy/ansible/blockchain.yml#L21).

* Extend this system to [implement a service handler](https://docs.ansible.com/ansible/2.6/user_guide/playbooks_intro.html#handlers-running-operations-on-change)
* Create a new variable to define the state of the service, so we can define which services start

**Comment by kdunn926** [comment]
Note: also need to be able to specify the var/state of each service for specific hosts.

**Comment by lazzarello** [comment]
closed with #18
