### ISSUE TITLE
Make blockchain playbook deploy to AWS

### ISSUE THREAD

**Issue by lazzarello** [quantstamp/eth-router#17]
The blockchain playbook was retro-fitted onto a manually configured server. it has never been run on a bare VM image. Bring the playbook to the level where it can run in AWS.

_this may be more than one ticket_

**Comment by kdunn926** [comment]
A few things I think we'll want to think about: 
- co-locating the proxy and blockchain nodes in the same VPC, to minimize firewall surface area and simplify the connectivity (e.g. not depend on reverse SSH tunnels)
- ensuring LVM is used by default on the blockchain nodes to allow attaching more storage, if needed
- periodically archiving chain data in an S3 bucket to allow _lightning speed_ initial sync for new nodes

**Comment by lazzarello** [comment]
I'm gonna close this since the DNS `stg.rpc.blockchaindevlabs.com` works with tokens. I'll make a new more specific issue regarding the staging and production environments.
